feat: hist_juxtaposition
ing-bank/popmon pull request #245
Opened 2022-08-15 14:28 UTC by pradyot-09

For now, the last_n is by default set to 2. Therefore, only two dates would appear in the dropdown. For the airline dataset if the last_n is set to max, popmon runs into the issue (for DEPARTURE feature) raised by Tomek https://github.com/ing-bank/popmon/issues/244.

<img width="1011" alt="Screenshot 2022-08-15 at 19 39 24" src="https://user-images.githubusercontent.com/20689007/184653380-bde9567b-915d-43b6-ad83-4d6aaab3c858.png">

closes ing-bank/popmon#230

2022-08-15 15:42 UTC, sbrugman requested changes
Nice work so far. The reports notebook needs to be updated so that the tests pass. After, it's easier to review the resulting report.

2022-08-15 15:42 UTC, sbrugman commented on popmon/visualization/templates/assets/js/custom-script.js
> +    $("button[data-feature-0='"+ obj.attr("data-feature") + "']").text("date: " + obj.text()) ;
`date` should be the (dynamic) time-axis name

2022-08-19 11:56 UTC, sbrugman commented
@pradyot-09 `popmon_tutorial_reports.ipynb` needs to be updated for the tests to pass

2022-08-19 16:01 UTC, sbrugman commented
The current implementation is a great step forward, as it allows users to view individual histograms, which wasn't possible before:

![image](https://user-images.githubusercontent.com/9756388/185659065-50af5b9e-e82e-4199-8cf4-ca6dd654b289.png)

The implementation might be better using two [plotly dropdowns](https://plotly.com/python/dropdowns/#update-several-data-attributes) in the same figure. This removes the redundant information that is now present in the plots: the reference is available both left and right, and histogram_prev1 is the same as histogram once selected.

2022-08-22 09:15 UTC, pradyot-09 commented
@sbrugman Just to clarify: A single plot with a dropdown to change the dates? asking because we discussed one of the main reason to have the plots side by side was to compare them.

2022-08-22 09:32 UTC, sbrugman commented
> @sbrugman Just to clarify: A single plot with a dropdown to change the dates? asking because we discussed one of the main reason to have the plots side by side was to compare them. 

Side-by-side or overlay should be both fine. The confusion in the current approach is the redundant information (histogram_prev1 may be the same as histogram in the other). You could consider adding the reference to the drop-down, and showing one histogram per drop-down.

2022-08-25 13:39 UTC, pradyot-09 commented
@sbrugman Have pushed the histogram plots with updatemenus. For static references the "histogram_ref" plots are repetitive. I think it would be clever to have the "histogram_ref" only once for static references. However, I think that we would need to pass the Settings object rather than the Report object to report_generation(). Not sure about the best way to get reference_type in histogram_section.
<img width="1011" alt="Screenshot 2022-08-25 at 18 12 54" src="https://user-images.githubusercontent.com/20689007/186678097-0946f5ce-14fb-499c-99da-16d54b841c7b.png">

2022-08-31 03:57 UTC, pradyot-09 commented
@sbrugman pushed the new histogram inspector with overlays. For now, I have kept double dropdowns for static reference too because I thought it was just very easy to disable overlays if needed. Let me know what you think.
<img width="1155" alt="Screenshot 2022-08-31 at 09 19 00" src="https://user-images.githubusercontent.com/20689007/187589317-8dd94ef5-137d-4775-ae28-4b501f7c022b.png">

2022-08-31 06:33 UTC, sbrugman commented on popmon/analysis/comparison/hist_comparer.py
> +# not required anymore?
This comment has crept in

2022-08-31 06:38 UTC, sbrugman commented on popmon/visualization/templates/assets/js/custom-script.js
> +    $("button.dropdown-toggle.feature").text("Feature: " + obj.text())
Probably ".feature" is causing the issue of the dropdown not updating

2022-08-31 06:38 UTC, sbrugman commented on popmon/visualization/templates/assets/css/custom-style.css
> +.dropdown-menu {
is this css needed?

2022-09-01 13:26 UTC, merged